# Generated by Django 2.2.7 on 2019-12-07 05:40

from django.db import migrations, models
import django_seo_inline.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='standart/')),
            ],
            bases=(django_seo_inline.mixins.SeoModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SampleSoloModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='solo/')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_seo_inline.mixins.SeoModelMixin, models.Model),
        ),
    ]
